name: Deploy docs to production
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.3.0
        env:
          NEXT_PUBLIC_BASE_PATH: "/design-system"
        with:
          cmd: boot # will run `yarn boot` command
      - uses: borales/actions-yarn@v2.3.0
        env:
          NEXT_PUBLIC_BASE_PATH: "/design-system"
        with:
          cmd: docs:export # will run `yarn build` command

      # Creates a .nojekyll file to disable github jekyll
      - name: Creating ".nojekyll" file
        run: sudo touch ./docs/out/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/out # The folder the action should deploy.
          clean: true
